### ISSUE TITLE
Change how memory usage is calculated

### ISSUE THREAD

**Issue by MaciejKozarzewski** [Gomocup/GomocupJudge#1]
Hi,
I want to talk about [update_vms()](https://github.com/Gomocup/GomocupJudge/blob/84f2361efa85dea6cf44a2456f9aaed4c1c0cce3/client/new_protocol.py#L95) method from new_protocol.py (and identical method in [cup20special](https://github.com/Gomocup/GomocupJudge/blob/84f2361efa85dea6cf44a2456f9aaed4c1c0cce3/cup20special/new_protocol.py#L96)).

Currently GomocupJudge uses [memory_info()](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_info) method from [psutil](https://psutil.readthedocs.io/en/latest/#) and extracts _vms_ field (virtual memory usage) which in my opinion is not correct. As an extreme example, I've recently run my engine on Linux where the memory usage was estimated to be over 9GB which was completely wrong - the amount of actually allocated resources was of the order of few MB + ~90MB of executable and libraries. I propose to switch to using [memory_full_info()](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_full_info) and extract _uss_ field. From the description it seems to fit perfectly to the needs of a manager:
> _uss_ is probably the most representative metric for determining how much memory is actually being used by a process. It represents the amount of memory that would be freed if the process was terminated right now.

In the same case as previously (on Linux) it reported about 120MB which is a very plausible result.

**Comment by accreator** [comment]
Hi,
Thanks for reporting the problem! We have replaced _vms_ with _uss_. Please reopen the issue if the problem has not been fully resolved.

**Comment by MaciejKozarzewski** [comment]
Oh, I just saw the change in code. I'm not sure, perhaps the way you implemented will work but I think the uss field of memory_full_info() cannot be accessed in this way. What I've been using in my code is d.memory_full_info()[7].
