### ISSUE TITLE
Wrapper21 not killing the engine

### ISSUE THREAD

**Issue by MaciejKozarzewski** [Gomocup/GomocupJudge#2]
The problem seems to be simple. In experimental tournament 2021 something happened that caused the client to restart the engine but it forgot to kill the first instance of the engine. Maybe it's just that the [stop](https://github.com/Gomocup/GomocupJudge/blob/84f2361efa85dea6cf44a2456f9aaed4c1c0cce3/wrapper21/client.py#L78) method of engine class should be called somewhere in the case of any crash?.

**Comment by accreator** [comment]
I tried fixing the problem. Please let us know if the problem persists.
(One thing to note is that if the engine has unexpected behaviors such as getting crashed that stuck the execution of END, the current implementation of the wrapper is not able to force kill the engine. This is fine though because the unlimited tournament does not expect crashes from the engine side during a game.)

**Comment by MaciejKozarzewski** [comment]
I'm not sure if this will solve the issue. Correct me if I'm wrong, but __del__ in python is not guaranteed to be executed at the moment when object goes out of scope, it depends on the garbage collector.

From my analysis of the problem:
read() in line 132 executed correctly - my engine produced the move
code in lines 133-165 also executed properly, as when the game resumed, my engine's move was present in the BOARD command, which means it was successfully sent to the server.

If an engine crashed it wouldn't be a problem , but it didn't. The main reason I'm putting pressure on solving this issue is that such abandoned (but still alive) instance of the engine will be running forever using up the hardware resources.

If you allow, I'll try to submit pull request with proposed solution.

**Comment by MaciejKozarzewski** [comment]
Ok, this is more or less the same idea I wanted to submit in a PR. I think this should fix the problem.
